/**
 * API origin & base paths.
 *
 * Dev (recommended — no CORS issues):
 *   VITE_API_BASE_URL=          (empty)
 *   VITE_API_PROXY_TARGET=https://api.karamstore.ly
 *   → browser calls same-origin /api, Vite proxies to remote
 *
 * Production build:
 *   VITE_API_BASE_URL=https://api.karamstore.ly
 *   → browser calls the real API host
 */

function stripTrailingSlash(url = '') {
  return String(url).replace(/\/+$/, '');
}

/** e.g. https://api.karamstore.ly — empty when using Vite proxy */
export const API_ORIGIN = stripTrailingSlash(import.meta.env.VITE_API_BASE_URL || '');

/** Media origin for /uploads */
export const MEDIA_ORIGIN = stripTrailingSlash(
  import.meta.env.VITE_MEDIA_BASE_URL || import.meta.env.VITE_API_BASE_URL || ''
);

/** Axios base — absolute remote API or relative `/api` for proxy */
export const API_BASE_URL = API_ORIGIN ? `${API_ORIGIN}/api` : '/api';

/**
 * Resolve media/upload paths returned by the API (e.g. `/uploads/images/x.jpg`).
 * @param {string} [url]
 * @returns {string}
 */
export function resolveMediaUrl(url) {
  if (!url) return '';
  const value = String(url).trim();
  if (!value) return '';
  if (/^(https?:|data:|blob:)/i.test(value)) return value;
  if (value.startsWith('//')) return `https:${value}`;

  const path = value.startsWith('/') ? value : `/${value}`;
  if (!MEDIA_ORIGIN) return path;
  return `${MEDIA_ORIGIN}${path}`;
}

/** Widths generated by the backend image optimizer (WebP variants). */
export const MEDIA_VARIANT_WIDTHS = [400, 800, 1200];

/**
 * Build a responsive absolute URL for a WebP size variant.
 * Master: `/uploads/images/{id}.webp`
 * Variant: `/uploads/images/{id}-{width}.webp`
 * @param {string} url absolute or relative media URL
 * @param {number} width
 */
export function mediaVariantUrl(url, width) {
  const absolute = resolveMediaUrl(url);
  if (!absolute || !/\.webp$/i.test(absolute) || /-\d+\.webp$/i.test(absolute)) {
    return absolute;
  }
  if (!width || width >= 1600) return absolute;
  return absolute.replace(/\.webp$/i, `-${width}.webp`);
}

/**
 * Whether this URL is an optimized local upload with size variants.
 * External/legacy JPEG etc. skip multi-size srcset.
 */
export function hasResponsiveVariants(url) {
  const absolute = resolveMediaUrl(url);
  if (!absolute) return false;
  if (/^(https?:|data:|blob:)/i.test(String(url).trim())) {
    // External absolute raw URL may not share our variants unless same host /uploads
    const pathOnly = absolute.replace(/^https?:\/\/[^/]+/i, '');
    return /\/uploads\/images\/[^/]+\.webp$/i.test(pathOnly) && !/-\d+\.webp$/i.test(pathOnly);
  }
  return /\/uploads\/images\/[^/]+\.webp$/i.test(absolute) && !/-\d+\.webp$/i.test(absolute);
}

/**
 * Build src + srcSet for product/banner images.
 * @param {string} [url]
 * @param {{ widths?: number[], preferSrcWidth?: number }} [options]
 * @returns {{ src: string, srcSet?: string }}
 */
export function buildResponsiveMedia(url, options = {}) {
  const absolute = resolveMediaUrl(url);
  if (!absolute) return { src: '' };

  if (!hasResponsiveVariants(url)) {
    return { src: absolute };
  }

  const widths = options.widths || MEDIA_VARIANT_WIDTHS;
  const usable = widths.filter((w) => w > 0 && w < 1600);
  const list = [...usable, 1600].filter((w, i, arr) => arr.indexOf(w) === i).sort((a, b) => a - b);

  const srcSet = list
    .map((w) => {
      const u = w >= 1600 ? absolute : mediaVariantUrl(url, w);
      return `${u} ${w}w`;
    })
    .join(', ');

  // Prefer smallest sensible file for default src (thumbs → 400; cards → 800)
  const prefer =
    options.preferSrcWidth ||
    (usable.length ? Math.min(800, Math.max(...usable)) : 800);
  const srcW = usable.includes(prefer)
    ? prefer
    : usable.find((w) => w >= prefer) || usable[usable.length - 1] || 800;
  const src = mediaVariantUrl(url, srcW) || absolute;
  return { src, srcSet };
}
