/** Central API path constants */
export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
  },
  products: '/products',
  colors: '/colors',
  sizes: '/sizes',
  brands: '/brands',
  categories: '/categories',
  inventory: {
    root: '/inventory',
    movements: '/inventory/movements',
    levels: '/inventory/levels',
    lowStock: '/inventory/low-stock',
    adjust: '/inventory/adjust',
    stocktakings: '/inventory/stocktakings',
  },
  purchases: '/purchases',
  suppliers: '/suppliers',
  banners: '/banners',
  orders: '/orders',
  customers: '/customers',
  settings: '/settings',
  cities: '/cities',
  shippingRates: '/shipping-rates',
  pos: {
    sale: '/pos/sale',
    recentOrders: '/pos/recent-orders',
  },
  store: {
    home: '/store/home',
    products: '/store/products',
    categories: '/store/categories',
    colors: '/store/colors',
    sizes: '/store/sizes',
    cities: '/store/cities',
    settings: '/store/settings',
    shippingCost: '/store/shipping-cost',
    orders: '/store/orders',
  },
  upload: '/upload',
  dashboard: '/dashboard',
  reports: {
    sales: '/reports/sales',
    profit: '/reports/profit',
    inventory: '/reports/inventory',
    products: '/reports/products',
  },
};
